
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.65vgnpc.mongodb.net/?retryWrites=true&w=majority
      database: tmbase
  mvc: 
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER